## Import Library yang digunakan

In [2]:
import pandas as pd    
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import numpy as np
import time

from scipy.special import beta as beta_func
import warnings
warnings.filterwarnings('ignore')

from scipy.stats import fisk, burr, kstest, anderson, chisquare

## Load dan Persiapan Data

Pada bagian ini dilakukan proses pembacaan data harga saham serta tahap awal pembersihan data sebelum dilakukan analisis lebih lanjut.

In [17]:
# Load data dan print data sebelum cleaning
df_saham = pd.read_csv("lq45_mar26_close.csv", index_col="Date", parse_dates=True)
df_saham.columns = df_saham.columns.str.replace('.JK', '', regex=False)
print(df_saham.head())

            AADI  ADMR        ADRO        AKRA  AMMN        AMRT        ANTM  \
Date
2017-01-02   NaN   NaN  422.978363  744.446777   NaN  569.011597  721.587830
2017-01-03   NaN   NaN  434.207947  722.733643   NaN  564.459595  713.525452
2017-01-04   NaN   NaN  424.226166  735.141174   NaN  528.042847  697.400513
2017-01-05   NaN   NaN  415.492004  725.835632   NaN  528.042847  701.431763
2017-01-06   NaN   NaN  422.978363  732.039124   NaN  537.147095  697.400513

                   ASII         BBCA         BBNI  ...  NCKL         PGAS  \
Date                                               ...
2017-01-02  5174.229492  2480.385498  1858.162354  ...   NaN  1641.824463
2017-01-03  5127.333496  2524.392090  1841.346436  ...   NaN  1714.794067
2017-01-04  5002.276855  2512.390381  1883.386475  ...   NaN  1745.198486
2017-01-05  5080.437012  2508.389893  1891.794434  ...   NaN  1739.117554
2017-01-06  5111.702148  2496.388428  1883.386475  ...   NaN  1726.956055

            PGEO        PTBA        SCMA         SMGR         TLKM  \
Date
2017-01-02   NaN  780.997070  400.979156  7381.625488  2602.451660
2017-01-03   NaN  798.178955  400.979156  7321.285156  2582.834961
2017-01-04   NaN  773.187012  413.867798  7602.874023  2582.834961
2017-01-05   NaN  752.881165  415.299866  7643.099609  2582.834961
2017-01-06   NaN  766.939087  421.028107  7562.645508  2615.529053

                  TOWR          UNTR         UNVR
Date
2017-01-02  551.627075  10805.506836  5740.633301
2017-01-03  551.627075  10678.380859  5744.330078
2017-01-04  539.300354  10881.779297  5947.769531
2017-01-05  542.381958  11174.162109  5999.553223
2017-01-06  542.381958  11034.326172  6006.951172

[5 rows x 45 columns]

### Menentukan Periode Data yang Konsisten

Setiap saham memiliki tanggal awal pencatatan yang berbeda. Oleh karena itu, dilakukan pencarian tanggal pertama yang valid untuk seluruh saham.

Tujuannya adalah agar analisis hanya menggunakan periode waktu di mana semua saham memiliki data lengkap.

In [18]:
# Cari saham yang paling baryu
all_first_dates = df_saham.apply(lambda col: col.first_valid_index())
first_valid_date = all_first_dates.max()
saham_terbaru = all_first_dates.idxmax()

print(saham_terbaru)
print(first_valid_date)

AADI
2024-12-05 00:00:00

### Pembersihan Data

Dataset disesuaikan agar hanya mencakup periode waktu yang sama untuk seluruh saham.

Langkah yang dilakukan:
- Memotong data berdasarkan tanggal awal bersama
- Menghapus nilai yang mengandung missing value (NaN)

Hal ini penting untuk menjaga konsistensi dalam perhitungan return dan kovarian.

In [19]:
# Slice semua data
df_saham = df_saham.loc[first_valid_date:]

# Hapus NaN
df_saham = df_saham.dropna(axis=0, how='any')

print(f'Shape data: {df_saham.shape}')
print(f'NaN: {df_saham.isna().sum().sum()}')
print(f'Range dataset: {df_saham.index.min()} s/d {df_saham.index.max()}')

# Print data setelah cleaning
print(df_saham.head())

Shape data: (306, 45)
NaN: 0
Range dataset: 2024-12-05 00:00:00 s/d 2026-03-30 00:00:00
                   AADI         ADMR         ADRO         AKRA    AMMN  \
Date
2024-12-05  6241.059082  1258.115356  1911.487671  1215.968994  9550.0
2024-12-06  7484.578125  1253.349731  1878.812622  1220.592529  9525.0
2024-12-09  8962.723633  1281.943237  2189.225098  1243.709595  9325.0
2024-12-10  9643.139648  1258.115356  2230.068848  1252.956665  9375.0
2024-12-11  9009.649414  1239.052979  2132.043945  1234.462769  9225.0

                   AMRT         ANTM         ASII         BBCA         BBNI  \
Date
2024-12-05  2951.072998  1419.330811  4788.159180  9464.409180  4071.646729
2024-12-06  3030.031494  1414.567993  4742.119141  9302.821289  4105.436523
2024-12-09  2901.723877  1419.330811  4811.178711  9556.745117  4223.699707
2024-12-10  3010.291748  1547.927979  4811.178711  9556.745117  4308.173828
2024-12-11  2931.333252  1524.113647  4834.198730  9625.997070  4287.055176

            ...        NCKL         PGAS        PGEO         PTBA        SCMA  \
Date        ...
2024-12-05  ...  781.995850  1418.346313  948.555908  2431.228027  120.317711
2024-12-06  ...  791.532349  1468.033569  938.925842  2422.354980  126.556404
2024-12-09  ...  801.068909  1504.169800  938.925842  2440.101074  136.360062
2024-12-10  ...  796.300659  1436.414429  934.110840  2511.085938  161.314850
2024-12-11  ...  781.995850  1449.965576  929.295837  2484.466553  160.423599

                   SMGR         TLKM        TOWR          UNTR         UNVR
Date
2024-12-05  3253.782959  2567.755371  693.061890  25260.691406  1758.353516
2024-12-06  3166.886719  2558.485352  683.436035  25557.875000  1753.664673
2024-12-09  3195.852051  2539.945557  702.687744  26060.802734  1777.109497
2024-12-10  3195.852051  2567.755371  693.061890  25786.478516  1875.577271
2024-12-11  3321.368896  2651.184082  688.248962  25397.853516  1823.998779

[5 rows x 45 columns]

### Visualisasi Harga Saham

Dilakukan visualisasi harga penutupan masing-masing saham dalam bentuk grafik time series.

In [ ]:
fig, axes = plt.subplots(nrows=len(df_saham.columns), ncols=1, figsize=(12, 6 * len(df_saham.columns)))

for i, stock_code in enumerate(df_saham.columns):
    axes[i].plot(df_saham.index, df_saham[stock_code], label=stock_code)
    axes[i].set_title(f"Grafik Harga Close Saham {stock_code}")
    axes[i].set_xlabel("Tanggal")
    axes[i].set_ylabel("Harga Close Saham")

    axes[i].xaxis.set_major_locator(mdates.MonthLocator())
    axes[i].xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.setp(axes[i].get_xticklabels(), rotation=45, ha="right")
    axes[i].legend()
    axes[i].grid(True)

plt.tight_layout()
plt.show()

### Perhitungan Log Return

Return saham dihitung menggunakan metode log return, yaitu:

$r_t = \ln \left(\frac{P_t}{P_{t-1}}\right)$.

Nilai NaN yang muncul akibat pergeseran data kemudian dihapus.

In [20]:
# Hitung log return
log_returns = np.log(df_saham / df_saham.shift(1))
print(log_returns)

log_returns.dropna().reset_index().to_csv("lq45_log_returns.csv", index=False)

                AADI      ADMR      ADRO      AKRA      AMMN      AMRT  \
Date
2024-12-05       NaN       NaN       NaN       NaN       NaN       NaN
2024-12-06  0.181695 -0.003795 -0.017242  0.003795 -0.002621  0.026404
2024-12-09  0.180230  0.022557  0.152908  0.018762 -0.021221 -0.043268
2024-12-10  0.073173 -0.018762  0.018485  0.007408  0.005348  0.036732
2024-12-11 -0.067951 -0.015267 -0.044951 -0.014870 -0.016129 -0.026580
...              ...       ...       ...       ...       ...       ...
2026-03-17  0.014389  0.046884  0.004090 -0.015687  0.026260  0.017452
2026-03-25  0.062304  0.022642  0.070896  0.050107  0.076881  0.053885
2026-03-26 -0.018059 -0.032873 -0.019194  0.000000 -0.020203 -0.043558
2026-03-27 -0.023042  0.012772 -0.015625  0.018623 -0.010257 -0.003431
2026-03-30  0.084872  0.025064  0.031010  0.050370  0.006167 -0.034969

                ANTM      ASII      BBCA      BBNI  ...      NCKL      PGAS  \
Date                                                ...
2024-12-05       NaN       NaN       NaN       NaN  ...       NaN       NaN
2024-12-06 -0.003361 -0.009662 -0.017221  0.008265  ...  0.012121  0.034432
2024-12-09  0.003361  0.014458  0.026929  0.028399  ...  0.011976  0.024317
2024-12-10  0.086732  0.000000  0.000000  0.019803  ... -0.005970 -0.046091
2024-12-11 -0.015504  0.004773  0.007220 -0.004914  ... -0.018127  0.009390
...              ...       ...       ...       ...  ...       ...       ...
2026-03-17  0.029772 -0.008584  0.003697  0.016074  ...  0.017622  0.030537
2026-03-25 -0.035282  0.129212  0.018282 -0.000145  ...  0.055216 -0.020254
2026-03-26 -0.053914 -0.054488 -0.003630 -0.009950  ... -0.046520 -0.047129
2026-03-27  0.020203 -0.020203 -0.025784 -0.025318  ...  0.000000 -0.016217
2026-03-30  0.000000  0.036076  0.004818 -0.012903  ... -0.035246  0.032174

                PGEO      PTBA      SCMA      SMGR      TLKM      TOWR  \
Date
2024-12-05       NaN       NaN       NaN       NaN       NaN       NaN
2024-12-06 -0.010204 -0.003656  0.050552 -0.027069 -0.003617 -0.013986
2024-12-09  0.000000  0.007299  0.074611  0.009105 -0.007273  0.027780
2024-12-10 -0.005141  0.028676  0.168059  0.000000  0.010889 -0.013793
2024-12-11 -0.005168 -0.010657 -0.005540  0.038523  0.031974 -0.006969
...              ...       ...       ...       ...       ...       ...
2026-03-17 -0.005277 -0.003431 -0.014706  0.036368  0.029952  0.069292
2026-03-25  0.051558  0.082419  0.029199  0.035091  0.078781  0.044997
2026-03-26  0.000000 -0.009539 -0.029199 -0.011561 -0.040191 -0.004008
2026-03-27  0.010000 -0.009631 -0.030077 -0.031499 -0.038590 -0.016195
2026-03-30  0.014815  0.016000 -0.023167 -0.016129 -0.003284  0.000000

                UNTR      UNVR
Date
2024-12-05       NaN       NaN
2024-12-06  0.011696 -0.002670
2024-12-09  0.019487  0.013280
2024-12-10 -0.010582  0.053928
2024-12-11 -0.015186 -0.027885
...              ...       ...
2026-03-17  0.017655  0.075262
2026-03-25  0.025505 -0.033040
2026-03-26  0.000812  0.002581
2026-03-27 -0.006515 -0.042111
2026-03-30  0.017011 -0.013532

[306 rows x 45 columns]

### Visualisasi Log Return

Setiap saham divisualisasikan dalam bentuk grafik log return.

In [ ]:
for column in log_returns.columns:
    plt.figure(figsize=(10, 6))
    
    plt.plot(log_returns.index, log_returns[column])
    plt.title(f'Grafik Return Saham {column}')
    plt.xlabel('Tanggal')
    plt.ylabel('Return')
    plt.grid(True)
    plt.show()

### Statistik Deskriptif Log Return

Dilakukan analisis statistik deskriptif terhadap log return, meliputi:
- mean
- standar deviasi
- nilai minimum dan maksimum

Analisis ini memberikan gambaran awal karakteristik distribusi return masing-masing saham.

In [31]:
log_returns.describe().T

,count,mean,std,min,25%,50%,75%,max
AADI,305.0,0.002053,0.033069,-0.126441,-0.014337,-0.002837,0.016314,0.181695
ADMR,305.0,0.001552,0.037866,-0.130362,-0.020101,0.000000,0.018265,0.222238
ADRO,305.0,0.001034,0.027882,-0.114739,-0.016261,0.000000,0.012685,0.152908
AKRA,305.0,0.000520,0.029397,-0.121214,-0.013668,0.000000,0.015504,0.200671
AMMN,305.0,-0.002201,0.041816,-0.160200,-0.021221,0.000000,0.020928,0.149898
AMRT,305.0,-0.002433,0.028113,-0.093434,-0.017938,-0.003431,0.012685,0.101003
ANTM,305.0,0.002959,0.035422,-0.155171,-0.016475,0.003221,0.023690,0.109699
ASII,305.0,0.000926,0.022714,-0.097374,-0.011385,0.000000,0.011929,0.129212
BBCA,305.0,-0.001257,0.017939,-0.089153,-0.011940,-0.002684,0.008253,0.073427
BBNI,305.0,-0.000184,0.022371,-0.079022,-0.012210,-0.002318,0.008265,0.085942
BBRI,305.0,-0.000365,0.021892,-0.106733,-0.012121,-0.002378,0.009346,0.088251
BBTN,305.0,0.000345,0.027371,-0.102760,-0.013730,-0.003914,0.011742,0.094879
BMRI,305.0,-0.000502,0.022707,-0.107500,-0.012321,-0.002006,0.009950,0.082960
BREN,305.0,-0.001030,0.040077,-0.222432,-0.016854,-0.002692,0.015222,0.179586
BRPT,305.0,0.001173,0.043378,-0.168228,-0.020305,0.000000,0.021506,0.157467
BUMI,305.0,0.001594,0.050188,-0.162119,-0.025533,0.000000,0.018868,0.277632
CPIN,305.0,-0.000604,0.023449,-0.098047,-0.012146,0.000000,0.010449,0.117261
CTRA,305.0,-0.001467,0.024058,-0.087011,-0.016173,0.000000,0.010989,0.076540
DSSA,305.0,0.001877,0.043013,-0.196688,-0.014011,0.004146,0.022035,0.182322
EMTK,305.0,0.001551,0.045480,-0.161388,-0.022557,0.000000,0.024293,0.220750
EXCL,305.0,0.001093,0.030544,-0.161602,-0.009174,0.000000,0.013072,0.145182
GOTO,305.0,-0.001201,0.031107,-0.156161,-0.017700,0.000000,0.014185,0.126041
HEAL,305.0,-0.000458,0.023898,-0.075637,-0.011606,0.000000,0.010545,0.128541
ICBP,305.0,-0.001558,0.018455,-0.075637,-0.011429,-0.002685,0.008097,0.064178
INCO,305.0,0.001155,0.038645,-0.162260,-0.020780,0.000000,0.021142,0.118920
INDF,305.0,-0.000805,0.018766,-0.075712,-0.012346,0.000000,0.011050,0.064539
INKP,305.0,0.001027,0.034238,-0.170730,-0.016000,0.000000,0.015687,0.152763
ISAT,305.0,-0.000509,0.034329,-0.166817,-0.016878,0.000000,0.017094,0.092457
ITMG,305.0,0.000717,0.014868,-0.065431,-0.004561,0.000897,0.006659,0.070658
JPFA,305.0,0.001075,0.030036,-0.109057,-0.017392,-0.002503,0.017094,0.101536
KLBF,305.0,-0.001466,0.027304,-0.073092,-0.020041,-0.003317,0.015346,0.092373
MAPI,305.0,-0.000694,0.031100,-0.160343,-0.017272,0.000000,0.015385,0.147636
MBMA,305.0,0.000880,0.047764,-0.162519,-0.027909,-0.004376,0.019231,0.223144
MDKA,305.0,0.001571,0.044239,-0.161969,-0.022060,0.000000,0.028259,0.159630
MEDC,305.0,0.001900,0.027362,-0.093932,-0.014052,0.000000,0.017544,0.145417
NCKL,305.0,0.001163,0.035293,-0.156569,-0.018692,0.000000,0.017622,0.168940
PGAS,305.0,0.000950,0.021629,-0.145050,-0.009917,0.000000,0.012500,0.072539
PGEO,305.0,0.000238,0.032295,-0.096918,-0.018215,-0.003527,0.012423,0.162056
PTBA,305.0,0.000849,0.016359,-0.058182,-0.008130,0.000000,0.007435,0.085656
SCMA,305.0,0.002476,0.045478,-0.156346,-0.023531,0.000000,0.020726,0.193653
SMGR,305.0,-0.000917,0.033141,-0.159195,-0.019048,-0.003683,0.014389,0.149096
TLKM,305.0,0.000554,0.025095,-0.127026,-0.014556,0.000000,0.013870,0.109434
TOWR,305.0,-0.001137,0.028632,-0.093332,-0.017392,0.000000,0.009479,0.137870
UNTR,305.0,0.000684,0.024516,-0.161737,-0.009872,0.001589,0.013296,0.068175
UNVR,305.0,0.000140,0.034692,-0.167433,-0.018544,-0.002670,0.017544,0.157490

### Distribusi Return Saham

Histogram log return ditampilkan untuk setiap saham.

Dua jenis histogram digunakan:
- density (probability density)
- frekuensi (count)

In [ ]:
for col in log_returns.columns:
    plt.figure()
    log_returns[col].hist(bins=50, density=True) 
    plt.title(f'Histogram (PDF) {col}')
    plt.xlabel('Return')
    plt.ylabel('Density')
    plt.show()

In [ ]:
for col in log_returns.columns:
    plt.figure()
    log_returns[col].hist(bins=50) 
    plt.title(f'Histogram {col}')
    plt.xlabel('Return')
    plt.ylabel('Frekuensi')
    plt.show()

## Estimasi Parameter Distribusi

Setelah distribusi return diidentifikasi melalui histogram, dilakukan estimasi parameter menggunakan metode **Maximum Likelihood Estimation (MLE)**.

Secara umum:

$L(\theta|x) = \prod_{i=1}^{n} f(x_i|\theta), \quad 
\ln L(\theta|x) = \sum_{i=1}^{n} \ln f(x_i|\theta)$

Contoh:

**Log-Logistik:**

$\ln L = \sum \left[ \ln \left(\frac{\alpha}{\beta}\right) + (\alpha-1)\ln \left(\frac{x_i-\gamma}{\beta}\right) - 2\ln \left(1+\left(\frac{x_i-\gamma}{\beta}\right)^\alpha\right) \right]$

**Burr (4P):**

$\ln L = \sum \left[ \ln \left(\frac{\alpha k}{\beta}\right) + (\alpha-1)\ln \left(\frac{x_i-\gamma}{\beta}\right) + (1-k)\ln \left(1+\left(\frac{x_i-\gamma}{\beta}\right)^\alpha\right) \right]$

Parameter diperoleh dengan menyelesaikan:

$\frac{\partial \ln L}{\partial \theta} = 0$

Karena tidak memiliki solusi analitik, estimasi dilakukan menggunakan software **EasyFit**.

In [6]:
df_param = pd.read_csv("nilai_parameter.csv")
print(df_param)

    No Saham         Model        k         alpha          beta         gamma
0    1  AADI     Burr (4P)  0.56587  1.027900e+02  1.279800e+00 -1.291700e+00
1    2  ADMR     Burr (4P)  0.57559  9.049300e+01  1.323200e+00 -1.337400e+00
2    3  ADRO  Log-Logistic      NaN  1.530500e+01  2.098300e-01 -2.110700e-01
3    4  AKRA     Burr (4P)  0.79324  3.199900e+02  4.263400e+00 -4.268000e+00
4    5  AMMN  Log-Logistic      NaN  2.040000e+08  4.450000e+06 -4.450000e+06
5    6  AMRT  Log-Logistic      NaN  5.143800e+01  7.813800e-01 -7.843700e-01
6    7  ANTM  Log-Logistic      NaN  7.850000e+06  1.510000e+05 -1.510000e+05
7    8  ASII     Burr (4P)  0.75371  1.020000e+08  1.040000e+06 -1.040000e+06
8    9  BBCA     Burr (4P)  0.75580  1.090000e+06  9.442700e+03 -9.442700e+03
9   10  BBNI     Burr (4P)  0.57290  2.943800e+04  2.682800e+02 -2.682900e+02
10  11  BBRI     Burr (4P)  0.65518  1.220000e+06  1.135800e+04 -1.135800e+04
11  12  BBTN     Burr (4P)  0.51255  1.740000e+07  1.790000e+05 -1.790000e+05
12  13  BMRI     Burr (4P)  0.85464  2.562100e+04  2.920400e+02 -2.920400e+02
13  14  BREN     Burr (4P)  0.72087  5.280000e+07  8.780000e+05 -8.780000e+05
14  15  BRPT  Log-Logistic      NaN  1.123800e+02  2.517600e+00 -2.517100e+00
15  16  BUMI     Burr (4P)  0.60641  3.332500e+02  6.733500e+00 -6.750600e+00
16  17  CPIN  Log-Logistic      NaN  3.296200e+02  3.886100e+00 -3.886700e+00
17  18  CTRA  Log-Logistic      NaN  2.309600e+01  3.001500e-01 -3.026300e-01
18  19  DSSA  Log-Logistic      NaN  8.810000e+05  1.851700e+04 -1.851700e+04
19  20  EMTK     Burr (4P)  0.67004  4.650000e+07  9.270000e+05 -9.270000e+05
20  21  EXCL     Burr (4P)  0.76768  1.391100e+03  1.766400e+01 -1.766900e+01
21  22  GOTO     Burr (4P)  0.41837  2.699500e+03  2.729300e+01 -2.731300e+01
22  23  HEAL     Burr (4P)  0.83904  1.535000e+04  1.770600e+02 -1.770700e+02
23  24  ICBP     Burr (4P)  0.86536  2.577000e+03  2.436500e+01 -2.436900e+01
24  25  INCO     Burr (4P)  0.76770  8.243400e+04  1.563900e+03 -1.564000e+03
25  26  INDF  Log-Logistic      NaN  1.610000e+08  1.660000e+06 -1.660000e+06
26  27  INKP     Burr (4P)  0.75722  1.950000e+08  3.010000e+06 -3.010000e+06
27  28  ISAT  Log-Logistic      NaN  4.620000e+07  8.140000e+05 -8.140000e+05
28  29  ITMG  Log-Logistic      NaN  7.534900e+01  5.297100e-01 -5.291600e-01
29  30  JPFA     Burr (4P)  0.65481  1.189100e+02  1.621500e+00 -1.631200e+00
30  31  KLBF     Burr (4P)  2.53460  4.791500e+00  1.205100e-01 -9.749000e-02
31  32  MAPI     Burr (4P)  0.77299  9.610000e+05  1.392800e+04 -1.392800e+04
32  33  MBMA     Burr (4P)  0.47740  1.521400e+02  2.562100e+00 -2.586900e+00
33  34  MDKA     Burr (4P)  0.89976  4.198800e+02  9.573200e+00 -9.575700e+00
34  35  MEDC  Log-Logistic      NaN  2.019200e+01  2.935400e-01 -2.929200e-01
35  36  NCKL     Burr (4P)  0.67006  1.360000e+05  2.179400e+03 -2.179400e+03
36  37  PGAS  Log-Logistic      NaN  2.790000e+08  3.180000e+06 -3.180000e+06
37  38  PGEO  Log-Logistic      NaN  1.149100e+01  1.845400e-01 -1.872200e-01
38  39  PTBA     Burr (4P)  0.62903  1.448200e+02  9.365700e-01 -9.412500e-01
39  40  SCMA     Burr (4P)  0.57092  6.630000e+06  1.190000e+05 -1.190000e+05
40  41  SMGR     Burr (4P)  0.66118  3.577300e+03  5.110800e+01 -5.112000e+01
41  42  TLKM     Burr (4P)  0.85804  1.560600e+04  1.996900e+02 -1.996900e+02
42  43  TOWR     Burr (4P)  0.73430  5.733400e+01  7.196500e-01 -7.280000e-01
43  44  UNTR     Burr (4P)  1.15260  4.530000e+05  5.529600e+03 -5.529600e+03
44  45  UNVR     Burr (4P)  0.66298  7.590000e+06  1.150000e+05 -1.150000e+05

## Uji Kesesuaian Distribusi

Model distribusi yang diperoleh kemudian diuji menggunakan:
- Kolmogorov-Smirnov (KS)
- Anderson-Darling (AD)
- Chi-Square (CS)

Hipotesis:

$H_0$: data mengikuti distribusi  
$H_1$: data tidak mengikuti distribusi  

Kriteria:

$A_{hitung} < A_{tabel} \Rightarrow H_0$ diterima  

Distribusi dianggap sesuai jika semua uji memenuhi kriteria.

Hasil estimasi parameter dan uji distribusi selanjutnya disajikan pada tabel berikut.

In [7]:
df_uji = pd.read_csv("asumsi_model.csv")
print(df_uji)

    Saham      Uji Distribusi Model Distribusi   A Tabel  A Hitung  \
0    AADI  Kolmogorov-Smirnov        Burr (4P)   0.07776   0.06871
1    AADI    Anderson Darling        Burr (4P)   2.50180   1.33340
2    AADI          Chi-Square        Burr (4P)  15.50700  13.91600
3    ADMR  Kolmogorov-Smirnov        Burr (4P)   0.07776   0.04707
4    ADMR    Anderson Darling        Burr (4P)   2.50180   0.72919
..    ...                 ...              ...       ...       ...
130  UNTR    Anderson Darling        Burr (4P)   2.50180   1.40520
131  UNTR          Chi-Square        Burr (4P)  15.50700  17.56400
132  UNVR  Kolmogorov-Smirnov        Burr (4P)   0.07776   0.06692
133  UNVR    Anderson Darling        Burr (4P)   2.50180   0.61636
134  UNVR          Chi-Square        Burr (4P)  15.50700  12.35400

             Kesimpulan Hipotesis
0    A Hitung < A Tabel  Diterima
1    A Hitung < A Tabel  Diterima
2    A Hitung < A Tabel  Diterima
3    A Hitung < A Tabel  Diterima
4    A Hitung < A Tabel  Diterima
..                  ...       ...
130  A Hitung < A Tabel  Diterima
131  A Hitung > A Tabel   Ditolak
132  A Hitung < A Tabel  Diterima
133  A Hitung < A Tabel  Diterima
134  A Hitung < A Tabel  Diterima

[135 rows x 7 columns]

## Seleksi Saham

Dilakukan seleksi saham berdasarkan hasil uji distribusi (KS, AD, CS).

Kriteria:
- Saham dipilih jika seluruh uji menerima $H_0$

Selanjutnya, model distribusi dan parameter untuk saham terpilih digabungkan sebagai input analisis berikutnya.

In [9]:
df_uji['Saham'] = df_uji['Saham'].str.strip()
df_uji['Hipotesis'] = df_uji['Hipotesis'].str.strip()
df_param['Saham'] = df_param['Saham'].str.strip()

summary = df_uji.groupby('Saham')['Hipotesis'].apply(lambda x: (x == 'Diterima').sum())
saham_diterima = summary[summary == 3].index

df_model = df_uji[df_uji['Saham'].isin(saham_diterima)]
df_model = df_model[['Saham', 'Model Distribusi']].drop_duplicates()

df_final = pd.merge(df_model, df_param, on='Saham', how='inner')

print(f"Jumlah saham lolos semua uji: {len(saham_diterima)}")
print(list(saham_diterima))

Jumlah saham lolos semua uji: 32
['AADI', 'ADMR', 'ADRO', 'AKRA', 'AMMN', 'AMRT', 'ANTM', 'ASII', 'BBRI', 'BMRI', 'BRPT', 'BUMI', 'CPIN', 'CTRA', 'EMTK', 'ICBP', 'INCO', 'INDF', 'INKP', 'ISAT', 'JPFA', 'KLBF', 'MAPI', 'MDKA', 'MEDC', 'NCKL', 'PGAS', 'PGEO', 'SCMA', 'SMGR', 'TLKM', 'UNVR']

## Data Hasil Seleksi

Data ini merupakan hasil seleksi dan akan digunakan pada tahap perhitungan selanjutnya.

In [ ]:
df_final.head(32)

,Saham,Model Distribusi,No,Model,k,alpha,beta,gamma
0,AADI,Burr (4P),1,Burr (4P),0.56587,1.027900e+02,1.279800e+00,-1.291700e+00
1,ADMR,Burr (4P),2,Burr (4P),0.57559,9.049300e+01,1.323200e+00,-1.337400e+00
2,ADRO,Log-Logistic (3P),3,Log-Logistic,NaN,1.530500e+01,2.098300e-01,-2.110700e-01
3,AKRA,Burr (4P),4,Burr (4P),0.79324,3.199900e+02,4.263400e+00,-4.268000e+00
4,AMMN,Log-Logistic (3P),5,Log-Logistic,NaN,2.040000e+08,4.450000e+06,-4.450000e+06
5,AMRT,Log-Logistic (3P),6,Log-Logistic,NaN,5.143800e+01,7.813800e-01,-7.843700e-01
6,ANTM,Log-Logistic (3P),7,Log-Logistic,NaN,7.850000e+06,1.510000e+05,-1.510000e+05
7,ASII,Burr (4P),8,Burr (4P),0.75371,1.020000e+08,1.040000e+06,-1.040000e+06
8,BBRI,Burr (4P),11,Burr (4P),0.65518,1.220000e+06,1.135800e+04,-1.135800e+04
9,BMRI,Burr (4P),13,Burr (4P),0.85464,2.562100e+04,2.920400e+02,-2.920400e+02
10,BRPT,Log-Logistic (3P),15,Log-Logistic,NaN,1.123800e+02,2.517600e+00,-2.517100e+00
11,BUMI,Burr (4P),16,Burr (4P),0.60641,3.332500e+02,6.733500e+00,-6.750600e+00
12,CPIN,Log-Logistic (3P),17,Log-Logistic,NaN,3.296200e+02,3.886100e+00,-3.886700e+00
13,CTRA,Log-Logistic (3P),18,Log-Logistic,NaN,2.309600e+01,3.001500e-01,-3.026300e-01
14,EMTK,Burr (4P),20,Burr (4P),0.67004,4.650000e+07,9.270000e+05,-9.270000e+05
15,ICBP,Burr (4P),24,Burr (4P),0.86536,2.577000e+03,2.436500e+01,-2.436900e+01
16,INCO,Burr (4P),25,Burr (4P),0.76770,8.243400e+04,1.563900e+03,-1.564000e+03
17,INDF,Log-Logistic (3P),26,Log-Logistic,NaN,1.610000e+08,1.660000e+06,-1.660000e+06
18,INKP,Burr (4P),27,Burr (4P),0.75722,1.950000e+08,3.010000e+06,-3.010000e+06
19,ISAT,Log-Logistic (3P),28,Log-Logistic,NaN,4.620000e+07,8.140000e+05,-8.140000e+05
20,JPFA,Burr (4P),30,Burr (4P),0.65481,1.189100e+02,1.621500e+00,-1.631200e+00
21,KLBF,Burr (4P),31,Burr (4P),2.53460,4.791500e+00,1.205100e-01,-9.749000e-02
22,MAPI,Burr (4P),32,Burr (4P),0.77299,9.610000e+05,1.392800e+04,-1.392800e+04
23,MDKA,Burr (4P),34,Burr (4P),0.89976,4.198800e+02,9.573200e+00,-9.575700e+00
24,MEDC,Log-Logistic (3P),35,Log-Logistic,NaN,2.019200e+01,2.935400e-01,-2.929200e-01
25,NCKL,Burr (4P),36,Burr (4P),0.67006,1.360000e+05,2.179400e+03,-2.179400e+03
26,PGAS,Log-Logistic (3P),37,Log-Logistic,NaN,2.790000e+08,3.180000e+06,-3.180000e+06
27,PGEO,Log-Logistic (3P),38,Log-Logistic,NaN,1.149100e+01,1.845400e-01,-1.872200e-01
28,SCMA,Burr (4P),40,Burr (4P),0.57092,6.630000e+06,1.190000e+05,-1.190000e+05
29,SMGR,Burr (4P),41,Burr (4P),0.66118,3.577300e+03,5.110800e+01,-5.112000e+01
30,TLKM,Burr (4P),42,Burr (4P),0.85804,1.560600e+04,1.996900e+02,-1.996900e+02
31,UNVR,Burr (4P),45,Burr (4P),0.66298,7.590000e+06,1.150000e+05,-1.150000e+05

## Perhitungan Expected Return dan Variansi

Pada tahap ini dihitung expected return dan variansi berdasarkan parameter distribusi yang diperoleh.

### 1. Distribusi Log-Logistik

Expected return:
$E(X) = \gamma + \beta \, B\left(1 + \frac{1}{\alpha}, 1 - \frac{1}{\alpha}\right)$

Variansi:
$\text{Var}(X) = \beta^2 \left[ B\left(1 + \frac{2}{\alpha}, 1 - \frac{2}{\alpha}\right) - \left(B\left(1 + \frac{1}{\alpha}, 1 - \frac{1}{\alpha}\right)\right)^2 \right]$


### 2. Distribusi Burr

Expected return:
$E(X) = \gamma + k\beta \, B\left(1 + \frac{1}{\alpha}, k - \frac{1}{\alpha}\right)$

Variansi:
$\text{Var}(X) = k\beta^2 B\left(1 + \frac{2}{\alpha}, k - \frac{2}{\alpha}\right) - k^2\beta^2 \left(B\left(1 + \frac{1}{\alpha}, k - \frac{1}{\alpha}\right)\right)^2$

dengan $B(\cdot,\cdot)$ adalah fungsi Beta.

In [12]:
def expected_return_loglogistic(alpha, beta_val, gamma):
    b = beta_func(1 + 1/alpha, 1 - 1/alpha)
    return gamma + beta_val * b

def varian_return_loglogistic(alpha, beta_val):
    b1 = beta_func(1 + 2/alpha, 1 - 2/alpha)
    b2 = beta_func(1 + 1/alpha, 1 - 1/alpha)
    return (beta_val**2) * (b1 - b2**2)

def expected_return_burr(k, alpha, beta_val, gamma):
    b = beta_func(1 + 1/alpha, k - 1/alpha)
    return gamma + k * beta_val * b

def varian_return_burr(k, alpha, beta_val):
    b1 = beta_func(1 + 2/alpha, k - 2/alpha)
    b2 = beta_func(1 + 1/alpha, k - 1/alpha)
    return k * (beta_val**2) * b1 - (k**2) * (beta_val**2) * (b2**2)

## Perhitungan Expected Return dan Variansi

Dilakukan perhitungan expected return dan variansi untuk setiap saham berdasarkan model distribusi (Log-Logistik atau Burr).

Hasil disimpan dalam bentuk tabel untuk digunakan pada tahap seleksi.

In [13]:
hasil = []

for i, row in df_final.iterrows():
    
    saham = row['Saham']
    model = row['Model Distribusi']
    
    k = row['k']
    alpha = row['alpha']
    beta_val = row['beta']
    gamma = row['gamma']
    
    try:
        if 'Log-Logistic' in model:
            er = expected_return_loglogistic(alpha, beta_val, gamma)
            vr = varian_return_loglogistic(alpha, beta_val)
        else:
            er = expected_return_burr(k, alpha, beta_val, gamma)
            vr = varian_return_burr(k, alpha, beta_val)
        
        hasil.append({
            'No': len(hasil) + 1,
            'Saham': saham,
            'Expected Return': er,
            'Varian Return': vr
        })
        
    except Exception as e:
        print(f"Error processing {saham}: {e}")
        
df_expretvar = pd.DataFrame(hasil)
print(df_expretvar)

df_expretvar.to_csv("expected_return_variance.csv", index=False)

    No Saham  Expected Return  Varian Return
0    1  AADI     2.137079e-03       0.000911
1    2  ADMR     1.775892e-03       0.001236
2    3  ADRO     2.407730e-04       0.000638
3    4  AKRA     8.615312e-04       0.000709
4    5  AMMN     1.862645e-09      -0.017588
5    6  AMRT    -2.504005e-03       0.000761
6    7  ANTM     3.987225e-09       0.001225
7    8  ASII     5.090405e-03      -0.000366
8    9  BBRI     7.231042e-03       0.000416
9   10  BMRI     3.059859e-03       0.000484
10  11  BRPT     8.279418e-04       0.001652
11  12  BUMI     2.084937e-03       0.002152
12  13  CPIN    -5.411644e-04       0.000457
13  14  CTRA    -1.552420e-03       0.000563
14  15  EMTK     1.456736e-02       0.001953
15  16  ICBP    -1.664422e-03       0.000329
16  17  INCO    -9.118785e-02       0.001474
17  18  INDF     4.656613e-10       0.000000
18  19  INKP     7.570224e-03       0.011719
19  20  ISAT     9.313226e-10       0.000441
20  21  JPFA     1.220004e-03       0.000913
21  22  KLBF    -1.475728e-03       0.000753
22  23  MAPI     6.544741e-03       0.000855
23  24  MDKA     1.660113e-03       0.001858
24  25  MEDC     1.807641e-03       0.000708
25  26  NCKL     1.170920e-02       0.001203
26  27  PGAS     0.000000e+00       0.002245
27  28  PGEO    -3.608762e-04       0.000897
28  29  SCMA     1.926905e-02       0.001802
29  30  SMGR    -1.160846e-03       0.000970
30  31  TLKM     3.345394e-03       0.000608
31  32  UNVR     1.139947e-02       0.001097

## Seleksi Saham

Saham dipilih dengan kriteria:
- $E(R) > 0$
- $\text{Var}(R) > 0$

Hasil seleksi digunakan sebagai kandidat portofolio.

In [14]:
df_selected = df_expretvar[
    (df_expretvar['Expected Return'] > 0) &
    (df_expretvar['Varian Return'] > 0)
].copy()

# reset nomor
df_selected = df_selected.reset_index(drop=True)
df_selected['No'] = df_selected.index + 1

print(df_selected)

df_selected.to_csv("saham_terpilih.csv", index=False)

    No Saham  Expected Return  Varian Return
0    1  AADI     2.137079e-03       0.000911
1    2  ADMR     1.775892e-03       0.001236
2    3  ADRO     2.407730e-04       0.000638
3    4  AKRA     8.615312e-04       0.000709
4    5  ANTM     3.987225e-09       0.001225
5    6  BBRI     7.231042e-03       0.000416
6    7  BMRI     3.059859e-03       0.000484
7    8  BRPT     8.279418e-04       0.001652
8    9  BUMI     2.084937e-03       0.002152
9   10  EMTK     1.456736e-02       0.001953
10  11  INKP     7.570224e-03       0.011719
11  12  ISAT     9.313226e-10       0.000441
12  13  JPFA     1.220004e-03       0.000913
13  14  MAPI     6.544741e-03       0.000855
14  15  MDKA     1.660113e-03       0.001858
15  16  MEDC     1.807641e-03       0.000708
16  17  NCKL     1.170920e-02       0.001203
17  18  SCMA     1.926905e-02       0.001802
18  19  TLKM     3.345394e-03       0.000608
19  20  UNVR     1.139947e-02       0.001097

## Matriks Kovarian

Menghitung matriks kovarian dari return saham terpilih.

Matriks ini merepresentasikan hubungan risiko antar saham dalam portofolio.

In [21]:
selected_stocks = df_selected['Saham'].tolist()

# ambil log return asli
df_return_selected = log_returns[selected_stocks]

df_cov_matrix = df_return_selected.cov()
print(df_cov_matrix)

df_cov_matrix.to_csv("covariance_matrix.csv")

          AADI      ADMR      ADRO      AKRA      ANTM      BBRI      BMRI  \
AADI  0.001094  0.000557  0.000492  0.000251  0.000182  0.000132  0.000160
ADMR  0.000557  0.001434  0.000632  0.000286  0.000490  0.000162  0.000171
ADRO  0.000492  0.000632  0.000777  0.000171  0.000283  0.000177  0.000217
AKRA  0.000251  0.000286  0.000171  0.000864  0.000284  0.000177  0.000179
ANTM  0.000182  0.000490  0.000283  0.000284  0.001255  0.000077  0.000082
BBRI  0.000132  0.000162  0.000177  0.000177  0.000077  0.000479  0.000362
BMRI  0.000160  0.000171  0.000217  0.000179  0.000082  0.000362  0.000516
BRPT  0.000102  0.000258  0.000181  0.000172  0.000288  0.000206  0.000199
BUMI  0.000471  0.000487  0.000282  0.000356  0.000424  0.000142  0.000214
EMTK  0.000253  0.000224  0.000121  0.000148  0.000218  0.000201  0.000256
INKP  0.000233  0.000504  0.000265  0.000263  0.000373  0.000218  0.000221
ISAT  0.000205  0.000384  0.000276  0.000179  0.000250  0.000247  0.000320
JPFA  0.000118  0.000072  0.000095  0.000137  0.000044  0.000127  0.000108
MAPI  0.000180  0.000261  0.000162  0.000309  0.000178  0.000200  0.000204
MDKA  0.000276  0.000607  0.000402  0.000362  0.000878  0.000154  0.000234
MEDC  0.000128  0.000288  0.000151  0.000243  0.000286  0.000070  0.000101
NCKL  0.000243  0.000539  0.000321  0.000242  0.000559  0.000153  0.000174
SCMA  0.000320  0.000303  0.000201  0.000234  0.000278  0.000151  0.000157
TLKM  0.000122  0.000224  0.000177  0.000155  0.000138  0.000184  0.000241
UNVR  0.000170  0.000264  0.000110  0.000214  0.000155  0.000214  0.000225

          BRPT      BUMI      EMTK      INKP      ISAT      JPFA      MAPI  \
AADI  0.000102  0.000471  0.000253  0.000233  0.000205  0.000118  0.000180
ADMR  0.000258  0.000487  0.000224  0.000504  0.000384  0.000072  0.000261
ADRO  0.000181  0.000282  0.000121  0.000265  0.000276  0.000095  0.000162
AKRA  0.000172  0.000356  0.000148  0.000263  0.000179  0.000137  0.000309
ANTM  0.000288  0.000424  0.000218  0.000373  0.000250  0.000044  0.000178
BBRI  0.000206  0.000142  0.000201  0.000218  0.000247  0.000127  0.000200
BMRI  0.000199  0.000214  0.000256  0.000221  0.000320  0.000108  0.000204
BRPT  0.001882  0.000748  0.000680  0.000380  0.000281  0.000191  0.000342
BUMI  0.000748  0.002519  0.000763  0.000506  0.000402  0.000325  0.000301
EMTK  0.000680  0.000763  0.002068  0.000481  0.000242  0.000233  0.000292
INKP  0.000380  0.000506  0.000481  0.001172  0.000341  0.000232  0.000275
ISAT  0.000281  0.000402  0.000242  0.000341  0.001179  0.000164  0.000263
JPFA  0.000191  0.000325  0.000233  0.000232  0.000164  0.000902  0.000133
MAPI  0.000342  0.000301  0.000292  0.000275  0.000263  0.000133  0.000967
MDKA  0.000474  0.000602  0.000482  0.000610  0.000322  0.000265  0.000279
MEDC  0.000168  0.000163  0.000078  0.000198  0.000097  0.000092  0.000081
NCKL  0.000347  0.000534  0.000524  0.000508  0.000236  0.000161  0.000342
SCMA  0.000620  0.000839  0.001436  0.000523  0.000259  0.000316  0.000262
TLKM  0.000219  0.000292  0.000292  0.000230  0.000435  0.000080  0.000193
UNVR  0.000174  0.000205  0.000291  0.000344  0.000224  0.000156  0.000210

          MDKA      MEDC      NCKL      SCMA      TLKM      UNVR
AADI  0.000276  0.000128  0.000243  0.000320  0.000122  0.000170
ADMR  0.000607  0.000288  0.000539  0.000303  0.000224  0.000264
ADRO  0.000402  0.000151  0.000321  0.000201  0.000177  0.000110
AKRA  0.000362  0.000243  0.000242  0.000234  0.000155  0.000214
ANTM  0.000878  0.000286  0.000559  0.000278  0.000138  0.000155
BBRI  0.000154  0.000070  0.000153  0.000151  0.000184  0.000214
BMRI  0.000234  0.000101  0.000174  0.000157  0.000241  0.000225
BRPT  0.000474  0.000168  0.000347  0.000620  0.000219  0.000174
BUMI  0.000602  0.000163  0.000534  0.000839  0.000292  0.000205
EMTK  0.000482  0.000078  0.000524  0.001436  0.000292  0.000291
INKP  0.000610  0.000198  0.000508  0.000523  0.000230  0.000344
ISAT  0.000322  0.000097  0.000236  0.000259  0.000435  0.000224
JPFA  0.000265  0.000092  0.000161  0.000316  0.000080  0.000156
MAPI  0.000279  0.000081  0.000342  0.000262  0.000193  0.000210
MDKA  0.001957  0.000420  0.000710  0.000616  0.000157  0.000362
MEDC  0.000420  0.000749  0.000163  0.000072  0.000098  0.000055
NCKL  0.000710  0.000163  0.001246  0.000470  0.000173  0.000320
SCMA  0.000616  0.000072  0.000470  0.002068  0.000203  0.000293
TLKM  0.000157  0.000098  0.000173  0.000203  0.000630  0.000166
UNVR  0.000362  0.000055  0.000320  0.000293  0.000166  0.001204

## Persiapan Parameter Optimasi

Menyusun parameter utama:
- $\mu$ : vektor expected return
- $e$ : vektor satuan
- $\Sigma$ : matriks kovarian
- $\Sigma^{-1}$ : invers kovarian

Parameter ini digunakan dalam proses optimasi portofolio.

In [ ]:
mu = df_selected['Expected Return'].values.reshape(-1, 1)
e = np.ones((len(mu), 1))
sigma = df_cov_matrix.values
sigma_inv = np.linalg.inv(sigma)

In [23]:
print("mu:\n", mu)

mu:
 [[2.13707909e-03]
 [1.77589150e-03]
 [2.40773014e-04]
 [8.61531161e-04]
 [3.98722477e-09]
 [7.23104202e-03]
 [3.05985912e-03]
 [8.27941793e-04]
 [2.08493678e-03]
 [1.45673594e-02]
 [7.57022388e-03]
 [9.31322575e-10]
 [1.22000388e-03]
 [6.54474095e-03]
 [1.66011281e-03]
 [1.80764057e-03]
 [1.17092031e-02]
 [1.92690542e-02]
 [3.34539386e-03]
 [1.13994702e-02]]

In [24]:
print("\ne:\n", e)

e:
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

In [25]:
print("\nsigma:\n", sigma)

sigma:
 [[1.09356822e-03 5.57321089e-04 4.91585201e-04 2.50750879e-04
  1.81974962e-04 1.31549761e-04 1.59756246e-04 1.02329814e-04
  4.71382927e-04 2.52912852e-04 2.32773054e-04 2.05072062e-04
  1.17518037e-04 1.80490612e-04 2.75959102e-04 1.28475282e-04
  2.42858915e-04 3.20043829e-04 1.21714688e-04 1.70201971e-04]
 [5.57321089e-04 1.43382297e-03 6.32383427e-04 2.85980754e-04
  4.90428066e-04 1.62405563e-04 1.70817450e-04 2.58190966e-04
  4.86783030e-04 2.23913396e-04 5.04303214e-04 3.84332984e-04
  7.19241895e-05 2.61030554e-04 6.07291931e-04 2.88060912e-04
  5.39464579e-04 3.02992014e-04 2.24121956e-04 2.64071420e-04]
 [4.91585201e-04 6.32383427e-04 7.77432249e-04 1.71193443e-04
  2.83037123e-04 1.76849056e-04 2.17427572e-04 1.80883395e-04
  2.82459428e-04 1.21137006e-04 2.65068271e-04 2.75641204e-04
  9.51453253e-05 1.62138636e-04 4.02302751e-04 1.51283063e-04
  3.21127019e-04 2.00834399e-04 1.76971881e-04 1.09907302e-04]
 [2.50750879e-04 2.85980754e-04 1.71193443e-04 8.64173171e-04
  2.84486719e-04 1.77398519e-04 1.79118386e-04 1.71952811e-04
  3.56417779e-04 1.47550547e-04 2.62777308e-04 1.79171171e-04
  1.36642930e-04 3.08738233e-04 3.61991091e-04 2.42806571e-04
  2.41787176e-04 2.34323359e-04 1.54614060e-04 2.14156241e-04]
 [1.81974962e-04 4.90428066e-04 2.83037123e-04 2.84486719e-04
  1.25469282e-03 7.66196068e-05 8.19194572e-05 2.87528364e-04
  4.23884934e-04 2.18112578e-04 3.72999869e-04 2.50480165e-04
  4.41237671e-05 1.77865531e-04 8.78477608e-04 2.85927434e-04
  5.59370557e-04 2.77738302e-04 1.37745589e-04 1.54521389e-04]
 [1.31549761e-04 1.62405563e-04 1.76849056e-04 1.77398519e-04
  7.66196068e-05 4.79272402e-04 3.61848391e-04 2.05547156e-04
  1.41979355e-04 2.01294667e-04 2.17702321e-04 2.47425219e-04
  1.26558169e-04 2.00100785e-04 1.53542708e-04 7.02798216e-05
  1.53175599e-04 1.50840963e-04 1.83730918e-04 2.13539213e-04]
 [1.59756246e-04 1.70817450e-04 2.17427572e-04 1.79118386e-04
  8.19194572e-05 3.61848391e-04 5.15585561e-04 1.99277027e-04
  2.14195204e-04 2.56332944e-04 2.21207143e-04 3.20395059e-04
  1.07647405e-04 2.04356542e-04 2.33649249e-04 1.00849090e-04
  1.73940236e-04 1.56871451e-04 2.40605613e-04 2.24863868e-04]
 [1.02329814e-04 2.58190966e-04 1.80883395e-04 1.71952811e-04
  2.87528364e-04 2.05547156e-04 1.99277027e-04 1.88164207e-03
  7.48309586e-04 6.80121567e-04 3.79820611e-04 2.80768994e-04
  1.90976103e-04 3.41983260e-04 4.74342038e-04 1.68237251e-04
  3.47364692e-04 6.19540919e-04 2.19050832e-04 1.73919259e-04]
 [4.71382927e-04 4.86783030e-04 2.82459428e-04 3.56417779e-04
  4.23884934e-04 1.41979355e-04 2.14195204e-04 7.48309586e-04
  2.51886795e-03 7.63232314e-04 5.05596144e-04 4.02281190e-04
  3.24708229e-04 3.01134727e-04 6.01959621e-04 1.63342016e-04
  5.34298309e-04 8.38914271e-04 2.91741704e-04 2.04722420e-04]
 [2.52912852e-04 2.23913396e-04 1.21137006e-04 1.47550547e-04
  2.18112578e-04 2.01294667e-04 2.56332944e-04 6.80121567e-04
  7.63232314e-04 2.06846667e-03 4.80581299e-04 2.42002410e-04
  2.32931753e-04 2.91804617e-04 4.82477397e-04 7.80516745e-05
  5.23876594e-04 1.43588405e-03 2.92180245e-04 2.90714028e-04]
 [2.32773054e-04 5.04303214e-04 2.65068271e-04 2.62777308e-04
  3.72999869e-04 2.17702321e-04 2.21207143e-04 3.79820611e-04
  5.05596144e-04 4.80581299e-04 1.17221419e-03 3.41438278e-04
  2.32436916e-04 2.74606953e-04 6.10026192e-04 1.97708734e-04
  5.07961911e-04 5.22815444e-04 2.30262461e-04 3.43867249e-04]
 [2.05072062e-04 3.84332984e-04 2.75641204e-04 1.79171171e-04
  2.50480165e-04 2.47425219e-04 3.20395059e-04 2.80768994e-04
  4.02281190e-04 2.42002410e-04 3.41438278e-04 1.17851032e-03
  1.63759292e-04 2.63239426e-04 3.22145879e-04 9.68267321e-05
  2.36398846e-04 2.59413548e-04 4.34573933e-04 2.23656446e-04]
 [1.17518037e-04 7.19241895e-05 9.51453253e-05 1.36642930e-04
  4.41237671e-05 1.26558169e-04 1.07647405e-04 1.90976103e-04
  3.24708229e-04 2.32931753e-04 2.32436916e-04 1.63759292e-04
  9.02134997e-04 1.32687733e-04 2.64980282e-04 9.20312480e-05
  1.61127429e-04 3.15687880e-04 7.96830885e-05 1.55725700e-04]
 [1.80490612e-04 2.61030554e-04 1.62138636e-04 3.08738233e-04
  1.77865531e-04 2.00100785e-04 2.04356542e-04 3.41983260e-04
  3.01134727e-04 2.91804617e-04 2.74606953e-04 2.63239426e-04
  1.32687733e-04 9.67192752e-04 2.78592297e-04 8.08134433e-05
  3.42010713e-04 2.61617840e-04 1.93049265e-04 2.09718629e-04]
 [2.75959102e-04 6.07291931e-04 4.02302751e-04 3.61991091e-04
  8.78477608e-04 1.53542708e-04 2.33649249e-04 4.74342038e-04
  6.01959621e-04 4.82477397e-04 6.10026192e-04 3.22145879e-04
  2.64980282e-04 2.78592297e-04 1.95708657e-03 4.20059131e-04
  7.10494513e-04 6.15565354e-04 1.56999398e-04 3.61594181e-04]
 [1.28475282e-04 2.88060912e-04 1.51283063e-04 2.42806571e-04
  2.85927434e-04 7.02798216e-05 1.00849090e-04 1.68237251e-04
  1.63342016e-04 7.80516745e-05 1.97708734e-04 9.68267321e-05
  9.20312480e-05 8.08134433e-05 4.20059131e-04 7.48692139e-04
  1.62601780e-04 7.23449846e-05 9.79923381e-05 5.47224856e-05]
 [2.42858915e-04 5.39464579e-04 3.21127019e-04 2.41787176e-04
  5.59370557e-04 1.53175599e-04 1.73940236e-04 3.47364692e-04
  5.34298309e-04 5.23876594e-04 5.07961911e-04 2.36398846e-04
  1.61127429e-04 3.42010713e-04 7.10494513e-04 1.62601780e-04
  1.24562588e-03 4.70493086e-04 1.73446982e-04 3.19796371e-04]
 [3.20043829e-04 3.02992014e-04 2.00834399e-04 2.34323359e-04
  2.77738302e-04 1.50840963e-04 1.56871451e-04 6.19540919e-04
  8.38914271e-04 1.43588405e-03 5.22815444e-04 2.59413548e-04
  3.15687880e-04 2.61617840e-04 6.15565354e-04 7.23449846e-05
  4.70493086e-04 2.06820952e-03 2.03049910e-04 2.93472351e-04]
 [1.21714688e-04 2.24121956e-04 1.76971881e-04 1.54614060e-04
  1.37745589e-04 1.83730918e-04 2.40605613e-04 2.19050832e-04
  2.91741704e-04 2.92180245e-04 2.30262461e-04 4.34573933e-04
  7.96830885e-05 1.93049265e-04 1.56999398e-04 9.79923381e-05
  1.73446982e-04 2.03049910e-04 6.29759668e-04 1.66168716e-04]
 [1.70201971e-04 2.64071420e-04 1.09907302e-04 2.14156241e-04
  1.54521389e-04 2.13539213e-04 2.24863868e-04 1.73919259e-04
  2.04722420e-04 2.90714028e-04 3.43867249e-04 2.23656446e-04
  1.55725700e-04 2.09718629e-04 3.61594181e-04 5.47224856e-05
  3.19796371e-04 2.93472351e-04 1.66168716e-04 1.20356507e-03]]

In [26]:
print("\nsigma inverse:\n", sigma_inv)

sigma inverse:
 [[ 1.45534132e+03 -2.28555345e+02 -7.35960358e+02 -1.86965889e+02
   5.75769379e+01  2.63536094e+01 -1.55088654e+01  1.07320365e+02
  -1.54141580e+02 -8.04773631e+01  3.92815543e+01  1.02301625e+01
  -2.84106939e+01 -4.91901387e+01  6.24566280e+01 -1.47663548e+01
   7.52428640e+01 -5.75010822e+01  1.11297052e+02 -7.45139428e+01]
 [-2.28555345e+02  1.38457570e+03 -7.51900717e+02 -2.51003805e+01
  -9.35826608e+01 -5.57695004e+01  3.25743198e+02  1.18602033e+01
  -4.28618375e+01  3.01979584e+01 -2.19083213e+02 -1.42979369e+02
   1.42549461e+02 -4.60482193e+01 -2.70513203e+01 -2.05855699e+02
  -1.76496289e+02  2.32769172e+01 -3.69319864e+01 -9.64544719e+01]
 [-7.35960358e+02 -7.51900717e+02  2.65787930e+03  1.20029524e+02
  -7.59230102e+01 -1.20076802e+02 -5.95121096e+02 -6.60971830e+01
   8.59474453e+01  2.05401396e+02  5.12060002e+01 -3.35200628e+01
  -6.46545963e+01  6.23368424e+01 -1.40356604e+02  5.48311051e+01
  -1.61101323e+02 -8.49223446e+01 -1.62658034e+02  2.07283825e+02]
 [-1.86965889e+02 -2.51003805e+01  1.20029524e+02  1.61210027e+03
  -1.62260560e+02 -2.39787714e+02 -9.85997030e+01  5.13208132e+01
  -9.05257956e+01  1.34846672e+02 -4.06444150e+01  6.72550446e+01
  -4.62565873e+01 -3.29875811e+02 -3.00459218e+01 -3.29238922e+02
   2.17910013e+01 -9.88181689e+01 -9.59176350e+01 -9.05306983e+01]
 [ 5.75769379e+01 -9.35826608e+01 -7.59230102e+01 -1.62260560e+02
   1.36407039e+03 -7.89151227e+01  3.00520635e+02 -2.44676129e+01
  -4.71535453e+01  2.96016668e+01 -2.31619059e+01 -1.06917682e+02
   1.57245960e+02  4.54871424e+01 -4.40727138e+02 -1.38943482e+02
  -3.00263627e+02  2.76136813e+01 -5.02751253e+01  5.22603078e+01]
 [ 2.63536094e+01 -5.57695004e+01 -1.20076802e+02 -2.39787714e+02
  -7.89151227e+01  4.77985228e+03 -3.05705008e+03 -1.64557023e+02
   1.49591767e+02  3.76700128e+01 -1.99399404e+02 -4.15326529e+00
  -2.40727444e+02 -1.62009439e+02  2.31006077e+02  9.68562937e+01
   8.09405243e+00 -4.39335561e+01  7.13075704e+00 -1.64501358e+02]
 [-1.55088654e+01  3.25743198e+02 -5.95121096e+02 -9.85997030e+01
   3.00520635e+02 -3.05705008e+03  5.04168213e+03  6.08842798e+01
  -9.02824610e+01 -3.04609606e+02  1.05471226e+01 -4.09349604e+02
   1.35669151e+02 -8.75993709e+01 -2.75948399e+02 -1.87530843e+02
   4.85249791e+00  2.56744903e+02 -5.08088849e+02 -1.86938926e+02]
 [ 1.07320365e+02  1.18602033e+01 -6.60971830e+01  5.13208132e+01
  -2.44676129e+01 -1.64557023e+02  6.08842798e+01  6.99538690e+02
  -1.33763950e+02 -1.15959920e+02 -3.36355497e+01 -1.96412270e+01
  -5.69833298e+00 -1.33069322e+02 -4.30921857e+01 -7.31114004e+01
   1.95653755e+01 -4.16998950e+01 -2.18602354e+01  1.12061004e+01]
 [-1.54141580e+02 -4.28618375e+01  8.59474453e+01 -9.05257956e+01
  -4.71535453e+01  1.49591767e+02 -9.02824610e+01 -1.33763950e+02
   5.67260567e+02 -3.43987421e+01 -3.80970215e+01 -4.75163932e+01
  -9.14189467e+01  2.12407395e+01 -8.47382923e+00  4.08440197e+01
  -7.07418716e+01 -8.70984565e+01 -7.29612574e+01  4.56290924e+01]
 [-8.04773631e+01  3.01979584e+01  2.05401396e+02  1.34846672e+02
   2.96016668e+01  3.76700128e+01 -3.04609606e+02 -1.15959920e+02
  -3.43987421e+01  1.07704382e+03 -4.06338422e+01  9.31974804e+01
   2.92735411e+01 -2.90450806e+01  1.99509675e+01 -1.66324707e+01
  -1.87057862e+02 -6.53796735e+02 -2.14857435e+02 -2.75885076e-03]
 [ 3.92815543e+01 -2.19083213e+02  5.12060002e+01 -4.06444150e+01
  -2.31619059e+01 -1.99399404e+02  1.05471226e+01 -3.36355497e+01
  -3.80970215e+01 -4.06338422e+01  1.32724032e+03 -8.03305060e+01
  -1.11768989e+02 -2.84512211e+01 -1.27784982e+02 -5.59487669e+01
  -1.86102804e+02 -1.02038075e+02 -7.82381463e+01 -1.16183026e+02]
 [ 1.02301625e+01 -1.42979369e+02 -3.35200628e+01  6.72550446e+01
  -1.06917682e+02 -4.15326529e+00 -4.09349604e+02 -1.96412270e+01
  -4.75163932e+01  9.31974804e+01 -8.03305060e+01  1.31476839e+03
  -9.24403396e+01 -8.63309349e+01 -1.25217462e+01  9.25232009e+01
   7.35106573e+01 -4.96257839e+01 -6.43407632e+02 -1.30414815e+01]
 [-2.84106939e+01  1.42549461e+02 -6.46545963e+01 -4.62565873e+01
   1.57245960e+02 -2.40727444e+02  1.35669151e+02 -5.69833298e+00
  -9.14189467e+01  2.92735411e+01 -1.11768989e+02 -9.24403396e+01
   1.29211486e+03 -3.14327658e+01 -1.12250844e+02 -9.54779294e+01
  -3.40113157e+01 -1.06688367e+02  5.04573971e+01 -5.30905322e+01]
 [-4.91901387e+01 -4.60482193e+01  6.23368424e+01 -3.29875811e+02
   4.54871424e+01 -1.62009439e+02 -8.75993709e+01 -1.33069322e+02
   2.12407395e+01 -2.90450806e+01 -2.84512211e+01 -8.63309349e+01
  -3.14327658e+01  1.36437528e+03  2.13513914e+00  9.08221107e+01
  -2.15456950e+02  1.60889442e+01 -9.03720588e+01 -1.65036942e+01]
 [ 6.24566280e+01 -2.70513203e+01 -1.40356604e+02 -3.00459218e+01
  -4.40727138e+02  2.31006077e+02 -2.75948399e+02 -4.30921857e+01
  -8.47382923e+00  1.99509675e+01 -1.27784982e+02 -1.25217462e+01
  -1.12250844e+02  2.13513914e+00  9.69772942e+02 -2.33651682e+02
  -1.49274089e+02 -1.20600974e+02  1.57056725e+02 -9.50879772e+01]
 [-1.47663548e+01 -2.05855699e+02  5.48311051e+01 -3.29238922e+02
  -1.38943482e+02  9.68562937e+01 -1.87530843e+02 -7.31114004e+01
   4.08440197e+01 -1.66324707e+01 -5.59487669e+01  9.25232009e+01
  -9.54779294e+01  9.08221107e+01 -2.33651682e+02  1.70767391e+03
   8.38327114e+01  1.00783680e+02 -1.19486493e+02  1.01677313e+02]
 [ 7.52428640e+01 -1.76496289e+02 -1.61101323e+02  2.17910013e+01
  -3.00263627e+02  8.09405243e+00  4.85249791e+00  1.95653755e+01
  -7.07418716e+01 -1.87057862e+02 -1.86102804e+02  7.35106573e+01
  -3.40113157e+01 -2.15456950e+02 -1.49274089e+02  8.38327114e+01
   1.35142537e+03  3.86611652e+01  2.10819306e+01 -1.19418046e+02]
 [-5.75010822e+01  2.32769172e+01 -8.49223446e+01 -9.88181689e+01
   2.76136813e+01 -4.39335561e+01  2.56744903e+02 -4.16998950e+01
  -8.70984565e+01 -6.53796735e+02 -1.02038075e+02 -4.96257839e+01
  -1.06688367e+02  1.60889442e+01 -1.20600974e+02  1.00783680e+02
   3.86611652e+01  1.05795902e+03  6.93814861e+01 -3.33882247e+01]
 [ 1.11297052e+02 -3.69319864e+01 -1.62658034e+02 -9.59176350e+01
  -5.02751253e+01  7.13075704e+00 -5.08088849e+02 -2.18602354e+01
  -7.29612574e+01 -2.14857435e+02 -7.82381463e+01 -6.43407632e+02
   5.04573971e+01 -9.03720588e+01  1.57056725e+02 -1.19486493e+02
   2.10819306e+01  6.93814861e+01  2.45395177e+03 -6.00705579e+01]
 [-7.45139428e+01 -9.64544719e+01  2.07283825e+02 -9.05306983e+01
   5.22603078e+01 -1.64501358e+02 -1.86938926e+02  1.12061004e+01
   4.56290924e+01 -2.75885076e-03 -1.16183026e+02 -1.30414815e+01
  -5.30905322e+01 -1.65036942e+01 -9.50879772e+01  1.01677313e+02
  -1.19418046e+02 -3.33882247e+01 -6.00705579e+01  1.02524045e+03]]